version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app

    networks:
      - laravel
    user: www-data

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "8187:80"
    depends_on:
      - app

    networks:
      - laravel

networks:
  laravel:
    driver: bridge
