name: Deployment to AWS EC2
on:
    push:
        branches: [main, dev]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              env:
                GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    set -ex
                    cd /var/www/html/oddly
                    sudo chown -R www-data:www-data .
                    sudo chmod -R 775 storage bootstrap/cache

                    # sudo git config --local credential.helper store
                    sudo echo "https://${{ env.GIT_USERNAME }}:${{ env.GIT_TOKEN }}@github.com" > ~/.git-credentials
                    sudo chmod 755 ~/.git-credentials

                    sudo git fetch origin main
                    sudo git reset --hard origin/main

                    # sudo git config --local --unset credential.helper
                    sudo rm ~/.git-credentials

                    sudo -u www-data composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
                    sudo -u www-data php artisan migrate --force
                    sudo npm run build
                    php artisan config:cache
                    php artisan route:cache
                    php artisan view:cache
    