name: Deployment to AWS EC2
on:
    push:
        branches: [main, dev]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              env:
                GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    set -ex
                    cd /var/www/html/oddly
                    sudo chown -R www-data:www-data .
                    sudo chmod -R 775 storage bootstrap/cache

                    sudo git config --global --add safe.directory /var/www/html/oddly
                    
                    sudo -u www-data git config credential.helper store
                    echo "https://${{ env.GIT_USERNAME }}:${{ env.GIT_TOKEN }}@github.com" | sudo -u www-data tee /var/www/html/oddly/.git-credentials > /dev/null
                    sudo chmod 600 /var/www/html/oddly/.git-credentials

                    sudo -u www-data git fetch origin main
                    sudo -u www-data git reset --hard origin/main

                    sudo -u www-data git config --unset credential.helper
                    sudo rm /var/www/html/oddly/.git-credentials

                    sudo -u www-data composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
                    sudo -u www-data php artisan migrate --force
                    sudo -u www-data npm run build
                    sudo -u www-data php artisan config:cache
                    sudo -u www-data php artisan route:cache
                    sudo -u www-data php artisan view:cache
    